list(Template = list(Machine = list(),
                     Materials = list(),
                     Measurements = list(),
                     Methods = list(),
                     Manpower = list(),
                     Environment = list(),
                     Management = list()),
     Topic = list(Logistics = list(),
                  Casting = list(Source = "https://www.researchgate.net/figure/ishikawa-diagram-for-squeeze-casting-process_fig1_306481048",
                                 `Die material` = c("Thermal conductivity",
                                                     "Surface finish",
                                                    "Mold material"),
                                 `Machining Parameters` = c("Pressing speed",
                                             "Squeeze pressure",
                                             "Time Delay/ Waiting time",
                                             "Pressure Duration"),
                                 `Die parameters` = c("Holding time",
                                                      "Temperature",
                                                      "Coating",
                                                      "Coat Thickness",
                                                      "Coat Adherence"),
                                 Material = c("Pouring temperature",
                                              "Alloy composition",
                                              "Thermal & Physical Characteristics",
                                              "Filling velocity",
                                              "Melt quality",
                                              "Melt quantity")),
                  `Laser Cutting` = list(Source = "https://www.researchgate.net/figure/A-fishbone-diagram-for-the-surface-roughness-in-CO2-laser-cutting_fig1_266282081",
                                         Environment = c("Humidity",
                                                         "Temperature"),
                                         `Laser beam properties` = c("Beam propagation factor",
                                                                     "Divergence",
                                                                     "TEM",
                                                                     "Diameter",
                                                                     "Wavelength"),
                                         Workpiece = c("Chemical",
                                                       "Surface state",
                                                       "Mechanical",
                                                       "Thermal",
                                                       "Optical",
                                                       "Type/ Thickness",
                                                       "Chemical"),
                                         
                                         `Machining Parameters` = c("Feed rate",
                                                                    "Coolant (dry)",
                                                                    "Coolant (wet)",
                                                                    "Depth of cut",
                                                                    "Cuttingspped"),
                                         Cuttingtool = c("Coatings",
                                                         "Tool Geometry",
                                                         "Material"),
                                         `Laser Parameters` = c("Laser power",
                                                                "Focal position",
                                                                "Nozzle type",
                                                                "Nozzle diameter",
                                                                "Stand-off distance",
                                                                "Gas pressure",
                                                                "Cutting speed",
                                                                "Spotsize",
                                                                "Angle"),
                                         Machine = c("Focal depth",
                                                     "Focal diameter",
                                                     "Focal length",
                                                     "Max. laser power",
                                                     "Mode of operation")),
                  Cutting = list(Source = "https://www.researchgate.net/figure/Fishbone-diagram-showing-parameters-and-machining-conditions-in-MQL-assisted-machining_fig6_272252279",
                                 `Fluid Application` = c("Flank face",
                                                         "Rake face"),
                                 Tool = c("Geometry",
                                          "Material",
                                          "Coating"),
                                 Nozzle = c("Distance from cutting zone",
                                            "Nozzle diameter",
                                            "nozzle inclination angle"),
                                 `Type of cutting` = c("Continious",
                                                       "Intermittend"),
                                 `Cutting parameters` = c("Cutting Speed",
                                                          "Feed Rate",
                                                          "Depth of cut"),
                                 `Cutting fluid` = c("Water soluble oil",
                                                     "Synthstic ester",
                                                     "Vegetable oil"),
                                 `Air and cutting fluid` = c("Fluid flow rate",
                                                             "Air flow rate",
                                                             "Supply pressure"),
                                 `Method of aerosol spray` = c("External spray",
                                                               "Internal spray")),
                  `Surface roughness` = list(Source = "https://www.semanticscholar.org/paper/Prediction-of-Machined-surface-Roughness-A-Review-Prabhakar-Kumar/14890bbedab9002cb965c0e9e617334e7b71a89d/figure/8",
                                             Tool = c("Ranout errors",
                                                      "Nose radius",
                                                      "Tool shape",
                                                      "Tool material"),
                                             Workpiece = c("Length",
                                                           "Width",
                                                           "Hardness"),
                                             `Machining parameters` = c("Process kinematics",
                                                                        "Cutting fluid",
                                                                        "Depth of cut",
                                                                        "Feed rate",
                                                                        "Cutting speed",
                                                                        "Tool angle",
                                                                        "Stepover"),
                                             `Cutting phenomena` = c("Cutting force variation",
                                                                     "Friction in the cutting zone",
                                                                     "Vibration",
                                                                     "Chip formation",
                                                                     "Accelerations")),
                  Grinding = list(Source = "https://www.researchgate.net/figure/Ishikawas-diagram-highlighting-different-parameters-that-could-impact-physical-quality_fig4_332515731",
                                  Machine = list(`Cutting Tool` = c("Abrasives",
                                                                    "Grain size",
                                                                    "Structure",
                                                                    "Dimension",
                                                                    "Runout error",
                                                                    "Nose radius"),
                                                 Others = c()),
                                  `Geometrical process parameters` = c("Size of jet mill",
                                                                       "Grinding nozzles type",
                                                                       "Grinding nozzle number and diameter",
                                                                       "Grinding nozzle angle",
                                                                       "Classifier gap",
                                                                       "Jet mill material",
                                                                       "Micronised product colection"),
                                  `Operating process parameters` = c("Grinding gas humidity",
                                                                     "Grinding pressure",
                                                                     "Injection pressure",
                                                                     "Solid feeding rate",
                                                                     "grinding gas type",
                                                                     "Grinding temperature"),
                                  `Raw materials` = c("Abrasives",
                                                      "Thoughness",
                                                      "Hardness",
                                                      "Stickiness",
                                                      "Morphology",
                                                      "Surface charges",
                                                      "Residual solvent",
                                                      "Crystal structure",
                                                      "Bulk density & flowability",
                                                      "Particel size distribution"),
                                  Materials = list(`Cutting Tool` = c("Chemical composition",
                                                                      "Mechanical properties",
                                                                      "Fracture anode"),
                                                   Workpiece = c("Workpiece length",
                                                                 "Workpiece diameter",
                                                                 "Workpiece hardness")),
                                  Measurements = list(),
                                  Methods = c("Work Speed", 
                                              "Wheel Speed", 
                                              "Depth of Cut", 
                                              "Feed Rate",
                                              "Cooling fluid",
                                              "Step over",
                                              "Tool angle",
                                              "Grinding wheel dressing"),
                                  Manpower = list(),
                                  Environment = c("Wet cutting", 
                                                  "Dry cutting",
                                                  "Grinding zone temperature",
                                                  "Acoustic emissions",
                                                  "Vibrations",
                                                  "Cutting force variations",
                                                  "Grind zone sparks",
                                                  "Chip formations",
                                                  "Friction in cutting zone"),
                                  Management = list())))